imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [FerSifpeBundle]
        directories: ["%kernel.root_dir%/../src"]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
          default:
              auto_mapping: true
              mappings:
                  sifpedomain:
                      mapping: true
                      type: annotation
                      dir:        %kernel.root_dir%/../src/Fer/SifpeDomain/
                      prefix:     Fer\SifpeDomain
                      alias:      FerSifpeDomain

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
            rss: false
            xml: false
            html: false
    format_listener: false
    body_converter:
      enabled: true
      validate: true
    body_listener:
       decoders:
           json: fos_rest.decoder.json

sphinxsearch:
   searchd:
       # Host name for your Sphinx daemon
       host: localhost
       # Port number for your Sphinx daemon
       port: 9312
   indexes:
       # List of sphinx index names (key) and entity names (value)
       # to use it in searchEx() method
       gastoidx: 'Fer\SifpeDomain\Model\Gasto'
       ingresoidx: 'Fer\SifpeDomain\Model\Ingreso'
