fer_sifpe_cuenta_show_rest:
    path:  /cuenta/{id}
    defaults: { _controller: FerSifpeBundle:Cuenta:show, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuenta_delete:
    path:  /cuenta/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Cuenta:delete, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuenta_delete_rest:
    path:  /cuenta/{id}
    defaults: { _controller: FerSifpeBundle:Cuenta:delete, _format: json }
    methods: [DELETE]
    options:
      expose: true

fer_sifpe_cuenta_save:
    path:  /cuenta
    defaults: { _controller: FerSifpeBundle:Cuenta:save, _format: json }
    methods: [POST]
    options:
      expose: true

fer_sifpe_cuenta_list:
    path:  /cuentas
    defaults: { _controller: FerSifpeBundle:Cuenta:listAll, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuenta_index:
    path:  /cuentas/gestion
    defaults: { _controller: FerSifpeBundle:Cuenta:index }
