fer_sifpe_cuenta_show_rest:
    pattern:  /cuenta/{id}
    defaults: { _controller: FerSifpeBundle:Cuenta:show, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuenta_delete:
    pattern:  /cuenta/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Cuenta:delete, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuenta_delete_rest:
    pattern:  /cuenta/{id}
    defaults: { _controller: FerSifpeBundle:Cuenta:delete, _format: json }
    methods: [DELETE]
    options:
      expose: true

fer_sifpe_cuetna_save:
    pattern:  /cuenta
    defaults: { _controller: FerSifpeBundle:Cuenta:save, _format: json }
    methods: [POST]
    options:
      expose: true

fer_sifpe_cuentas_list:
    pattern:  /cuentas
    defaults: { _controller: FerSifpeBundle:Cuenta:listAll, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_cuentas_list:
    pattern:  /cuentas
    defaults: { _controller: FerSifpeBundle:Cuenta:listAll, _format: json }
    methods: [GET]
    options:
      expose: true