fer_sifpe_empresa_index:
    path:  /empresas/gestion
    defaults: { _controller: FerSifpeBundle:Empresa:index }

fer_sifpe_empresa_save:
    path:  /empresa
    defaults: { _controller: FerSifpeBundle:Empresa:save, _format: json }
    methods: [POST]
    options:
      expose: true

fer_sifpe_empresa_list:
    path:  /empresas
    defaults: { _controller: FerSifpeBundle:Empresa:listAll, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_empresa_delete:
    path:  /empresa/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Empresa:delete, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_empresa_delete_rest:
    path:  /empresa/{id}
    defaults: { _controller: FerSifpeBundle:Empresa:delete, _format: json }
    methods: [DELETE]
    options:
      expose: true

fer_sifpe_empresa_save:
    path:  /empresa
    defaults: { _controller: FerSifpeBundle:Empresa:save, _format: json }
    methods: [POST]
    options:
      expose: true

fer_sifpe_empresa_show_rest:
    path:  /empresa/{id}
    defaults: { _controller: FerSifpeBundle:Empresa:show, _format: json }
    methods: [GET]
    options:
      expose: true

