fer_sifpe_ingreso_delete:
    pattern:  /ingreso/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Ingreso:delete, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_ingreso_delete_rest:
    pattern:  /ingreso/{id}
    defaults: { _controller: FerSifpeBundle:Ingreso:delete, _format: json }
    methods: [DELETE]
    options:
      expose: true

fer_sifpe_ingreso_show:
    pattern:  /ingreso/{id}
    defaults: { _controller: FerSifpeBundle:Ingreso:show, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_ingreso_save:
    pattern:  /ingreso
    defaults: { _controller: FerSifpeBundle:Ingreso:save, _format: json }
    methods: [POST]
    options:
      expose: true


fer_sifpe_ingreso_list_all:
    pattern:  /ingresos
    defaults: { _controller: FerSifpeBundle:Ingreso:listAll, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_ingreso_list:
    pattern:  /ingresos/{desdeMeses}
    defaults: { _controller: FerSifpeBundle:Ingreso:listDesdeMes, _format: json, desdeMeses: 0 }
    methods: [GET]
    options:
      expose: true

