fer_sifpe_default:
    pattern:  /
    defaults: { _controller: FerSifpeBundle:Gasto:index }

fer_sifpe_gasto_index:
    pattern:  /gastos/gestion
    defaults: { _controller: FerSifpeBundle:Gasto:index }

fer_sifpe_ingreso_index:
    pattern:  /ingresos/gestion
    defaults: { _controller: FerSifpeBundle:Ingreso:index }

fer_sifpe_gasto_delete:
    pattern:  /gasto/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Gasto:delete, _format: json }
    methods: [GET]

fer_sifpe_ingreso_delete:
    pattern:  /ingreso/{id}/borrar/
    defaults: { _controller: FerSifpeBundle:Ingreso:delete, _format: json }
    methods: [GET]

fer_sifpe_gasto_xcuenta:
    pattern:  /cuentas/gastos/{anio}/{mes}
    defaults: { _controller: FerSifpeBundle:Gasto:listResumenPorCuenta, _format: json}
    methods: [GET]

fer_sifpe_ingreso_xcuenta:
    pattern:  /cuentas/ingresos/{anio}/{mes}
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenPorCuenta, _format: json}
    methods: [GET]

fer_sifpe_gasto_xanio:
    pattern:  /{anio}/gastos/resumen
    defaults: { _controller: FerSifpeBundle:Gasto:listResumenAnual, _format: json }
    methods: [GET]

fer_sifpe_ingreso_xanio:
    pattern:  /{anio}/ingresos/resumen
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenAnual, _format: json }
    methods: [GET]

fer_sifpe_gasto_list:
    pattern:  /gastos/{desdeMeses}
    defaults: { _controller: FerSifpeBundle:Gasto:listDesdeMes, _format: json, desdeMeses: 0 }
    methods: [GET]

fer_sifpe_gasto_save:
    pattern:  /gasto
    defaults: { _controller: FerSifpeBundle:Gasto:save, _format: json }
    methods: [POST]

fer_sifpe_empresa_save:
    pattern:  /empresa
    defaults: { _controller: FerSifpeBundle:Empresa:save, _format: json }
    methods: [POST]

fer_sifpe_ingreso_list:
    pattern:  /ingresos/{desdeMeses}
    defaults: { _controller: FerSifpeBundle:Ingreso:listDesdeMes, _format: json, desdeMeses: 0 }
    methods: [GET]

fer_sifpe_resumen_xcuenta:
    pattern:  /{anio}/{mes}/resumen
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenMes, _format: json }
    methods: [GET]

fer_sifpe_empresas_list:
    pattern:  /empresas
    defaults: { _controller: FerSifpeBundle:Empresa:listAll, _format: json }
    methods: [GET]

fer_sifpe_cuentas_list:
    pattern:  /cuentas
    defaults: { _controller: FerSifpeBundle:Cuenta:listAll, _format: json }
    methods: [GET]