fer_sifpe_default:
    path:  /
    defaults: { _controller: FerSifpeBundle:Gasto:index }

gasto_routing:
    resource: "@FerSifpeBundle/Resources/config/gasto_routing.yml"

ingreso_routing:
    resource: "@FerSifpeBundle/Resources/config/ingreso_routing.yml"

cuenta_routing:
    resource: "@FerSifpeBundle/Resources/config/cuenta_routing.yml"

grupocuenta_routing:
    resource: "@FerSifpeBundle/Resources/config/grupocuenta_routing.yml"

empresa_routing:
    resource: "@FerSifpeBundle/Resources/config/empresa_routing.yml"

fer_sifpe_gasto_xcuenta:
    path:  /cuentas/gastos/{anio}/{mes}
    defaults: { _controller: FerSifpeBundle:Gasto:listResumenPorCuenta, _format: json}
    methods: [GET]
    options:
      expose: true

fer_sifpe_ingreso_xcuenta:
    path:  /cuentas/ingresos/{anio}/{mes}
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenPorCuenta, _format: json}
    methods: [GET]
    options:
      expose: true

fer_sifpe_gasto_xanio:
    path:  /{anio}/gastos/resumen
    defaults: { _controller: FerSifpeBundle:Gasto:listResumenAnual, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_ingreso_xanio:
    path:  /{anio}/ingresos/resumen
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenAnual, _format: json }
    methods: [GET]
    options:
      expose: true

fer_sifpe_resumen_xcuenta:
    path:  /{anio}/{mes}/resumen
    defaults: { _controller: FerSifpeBundle:Ingreso:listResumenMes, _format: json }
    methods: [GET]
    options:
      expose: true
