parameters:
  fer_sifpe.gasto_repository.class: Fer\SifpeDomain\Repository\ORM\GastoRepository
  fer_sifpe.gasto_repository.factory_argument: 'Fer\SifpeDomain\Model\Gasto'
  fer_sifpe.ingreso_repository.class: Fer\SifpeDomain\Repository\ORM\IngresoRepository
  fer_sifpe.ingreso_repository.factory_argument: 'Fer\SifpeDomain\Model\Ingreso'
  fer_sifpe.empresa_repository.class: Fer\SifpeDomain\Repository\ORM\EmpresaRepository
  fer_sifpe.empresa_repository.factory_argument: 'Fer\SifpeDomain\Model\Empresa'
  fer_sifpe.cuenta_repository.class: Fer\SifpeDomain\Repository\ORM\CuentaRepository
  fer_sifpe.cuenta_repository.factory_argument: 'Fer\SifpeDomain\Model\Cuenta'
  fer_sifpe.grupocuenta_repository.class: Fer\SifpeDomain\Repository\ORM\GrupoCuentaRepository
  fer_sifpe.grupocuenta_repository.factory_argument: 'Fer\SifpeDomain\Model\GrupoCuenta'
  fer_sifpe.apunte_service.class: Fer\SifpeBundle\Service\ApunteService
  fer_sifpe.entity_service.class: Fer\SifpeBundle\Service\EntityService

services:
  fer_sifpe.gasto_repository:
    class:           %fer_sifpe.gasto_repository.class%
    factory:	     ['@doctrine.orm.entity_manager', getRepository]
    arguments:
        - %fer_sifpe.gasto_repository.factory_argument%

  fer_sifpe.ingreso_repository:
    class:           %fer_sifpe.ingreso_repository.class%
    factory: 	     ['@doctrine.orm.entity_manager', getRepository]
    arguments:
        - %fer_sifpe.ingreso_repository.factory_argument%

  fer_sifpe.empresa_repository:
    class:           %fer_sifpe.empresa_repository.class%
    factory: 	     ['@doctrine.orm.entity_manager', getRepository]
    arguments:
        - %fer_sifpe.empresa_repository.factory_argument%

  fer_sifpe.cuenta_repository:
      class:           %fer_sifpe.cuenta_repository.class%
      factory:         ['@doctrine.orm.entity_manager',getRepository]
      arguments:
          - %fer_sifpe.cuenta_repository.factory_argument%

  fer_sifpe.grupocuenta_repository:
      class:           %fer_sifpe.grupocuenta_repository.class%
      factory: 	       ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - %fer_sifpe.grupocuenta_repository.factory_argument%

########################################
# Servicios para manejar entidades
########################################

  fer_sifpe.gasto_service:
    class: %fer_sifpe.apunte_service.class%
    arguments:
      - '@fer_sifpe.gasto_repository'
      - '@fos_elastica.finder.website.gasto'

  fer_sifpe.ingreso_service:
      class: %fer_sifpe.apunte_service.class%
      arguments:
        - '@fer_sifpe.ingreso_repository'
        - '@fos_elastica.finder.website.ingreso'

  fer_sifpe.cuenta_service:
      class: %fer_sifpe.entity_service.class%
      arguments:
        - '@fer_sifpe.cuenta_repository'

  fer_sifpe.empresa_service:
      class: %fer_sifpe.entity_service.class%
      arguments:
        - '@fer_sifpe.empresa_repository'

  fer_sifpe.grupocuenta_service:
      class: %fer_sifpe.entity_service.class%
      arguments:
        - '@fer_sifpe.grupocuenta_repository'
