parameters:
#    fer_sifpe.example.class: Fer\SifpeBundle\Example

services:
#    fer_sifpe.example:
#        class: %fer_sifpe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
